cols_to_eng = {
    "от куда пациент": "from",
    "N ПАЦИЕНТА(КРОВЬ)": "blood_id",
    "Пол ( 1-м, 2-ж)": "sex",
    "КАРТА ПАЦ-ТА": "man_id",
    "Количество суток с начала заболевания до госпитализации": "ill_to_hosp",
    "Дата начала лечения": "date_start_treat",
    "День заболевания": "date_ill",
    "Исходы (1 умер, 2 выписка)": "death",
    "Степень тяжести заболевания (1-легкая, 2-средняя, 3-тяжелая и кр.тяжелая)": "severity",
    "ДАТА РОЖДЕНИЯ (ВОЗРАСТ)": "age",
    "СЕКВЕНАТОР": "seq_machine",
    "НАЗВАНИЕ БИБЛИОТЕКИ (ЗАПУСКА)": "launch_name",
    "ДАТА ЗАПУСКА": "launch_date",
    "ИНДЕКС": "index",
    "ГРУППА": "group",
    "ЛЕЧЕНИЕ": "treatment",
    "Койко-дней": "days_at_hosp",
    "Мутаци в гене ITGAM": "ITGAM_mut",
    "rs мутации": "rs_mut",
    "Повышение температуры": "temp",
    "Слабость": "weakness",
    "Потеря обонания и вкуса": "smell_taste_loss",
    "ИБС": "chd",  # ишемическая болезнь сердца
    "АКС": "aks",  # ??
    "ЦВБ": "cvd",  # Цереброваскулярная болезнь
    "Количество суток на ИВЛ": "imv_days",
    "МазокПЦР1": "pcr_1",
    "Лейк1": "leuk_1",
    "Нейтр1": "neut_1",  # нейтрофилы(?)
    "Л1": "l_1",  # ??
    "ЛДГ1": "ldh_1",  # Лактатдегидрогеназа
    "СРБ1": "crp_1",  # с-реактивный белок
    "Фер1": "fer_1",
    "Д-димер1": "d_dym_1",
    "ИЛ-6_1": "il6_1",
    "Креатинин1": "creat_1",
    "Глюкоза1": "glu_1",
    "МазокПЦР3": "pcr_3",
    "Лейк3": "leuk_3",
    "Нейтр3": "neut_3",
    "Л3": "l_3",
    "ЛДГ3": "ldh_3",
    "СРБ3": "crp_3",
    "Фер3": "fer_3",
    "Д-димер3": "d_dym_3",
    "ИЛ-6_3": "il6_3",
    "Креатинин3": "creat_3",
    "Глюкоза3": "glu_3",
    "Мазок ПЦР5": "pcr_5",
    "Лейк5": "leuk_5",
    "Нейтр5": "neut_5",
    "Л5": "l_5",
    "ЛДГ5": "ldh_5",
    "СРБ_5": "crp_5",
    "Фер_5": "fer_5",
    "Д-димер5": "d_dym_5",
    "ИЛ-6_5": "il6_5",
    "Креатинин5": "creat_5",
    "Глюкоза5": "glu_5",
    "Лейк7": "leuk_7",
    "Нейтр7": "neut_7",
    "Л7": "l_7",
    "ЛДГ7": "ldh_7",
    "СРБ_7": "crp_7",
    "Фер_7": "fer_7",
    "Д-димер7": "d_dym_7",
    "ИЛ-6_7": "il6_7",
    "Креатинин7": "creat_7",
    "Глюкоза7": "glu_7",
    "Мазок ПЦР 9-10": "pcr_9",
    "Прокальцитонин": "pct",  # Procalcitonin (hehh???)
    "NEWS при поступлении (сумма баллов):": "news_1",  # National Early Warning Score (NEWS)
    "Степень дыхательной недостаточности на 5й день от поступления: ": "resp_fail_5",
    "NEWS на 5й день от поступления": "news_5",
    "Степень дыхательной недостаточности при выписке": "resp_fail_out",
    "NEWS при выписке (сумма баллов):": "news_out",
    'ШТОРМ 1-да, 0-нет':'storm',
 'Цитокины Биобанк':'cytokines_biobank',
 'Кашель':'cough',
 'Одышка':'sydpnea',
 'Тяжесть в груди':'chest_heaviness',
 'СД':'diabetes', #????
 'Рав.артрит (или другие автоиммуные заб)':'autoimmune',
 'ХБП 3-5':'ckd_3_5', #chronic kidney disease
 'ХОБЛ':'COPD', #Chronic obstructive pulmonary disease 
 'Бронхиальная астма':'asthma',
 'Хронический бронхит':'bronchitis',
 'ГБ':'hypertension', #????
 'ОИМ (свежий)':'mi', #Острый инфаркт миокарда Myocardial infarction
 'Состояние после инфаркта (ПИКС)':'PIKS', #Постинфарктный кардиосклероз 
 'Нарушения ритма':'arrhythmia',
 'ХСН (0-нет, 1-да) ':'chf', #Хроническая сердечная недостаточность
 'Риск ССО':'heart_score',
 'Другое':'other', #???
 'ОНМК (свежий)':'cerebral_infarction', #острое нарушение мозгового кровообращения
 'Тип ОНМК (1-ишемический, 2-геморрагический)':'cerebral_infarction_type_1i_2h',
 'Последствия ОНМК':'cerebral_infarction_effects',
 'Другое.1':'other_1',
 'Онкологические заболевания':'oncology',
 'Стадия':'stage_cancer', #??
 'Первичный очаг':'primary_focus_cancer',
 'Свежие операции или травмы':'fresh_surgery',
 'Операции в анамнезе':'anamnes_surgery',
 'Заболевания ЖКТ':'git_diseases',
 'Заболевания почек':'kidneys_diseases',
 'Анемия':'anemia',
 'Степень анемии (1-легкая, 2-средняя, 3-тяжелая)':'anemia_stage',
 'Хроническая ЛОР-патология':'chronic_ent_pathology',
 'Ожирение':'obesity',
 'Степень':'obesity_stage', #???
 'Другое.2':'other_2',
 'Степень дыхательной недостаточности при поступлении':'respiratory_failure_stage_day0',
 'Интраальвеолярный отёк':'intraalveolar_edema',
 'Полнокровие кровеносных сосудов':'blood_vessels_congestion',
 'Деструктивно-продуктивный васкулит':'destructive-productive_vasculitis',
 'Cладжи эритроцитов с их лизисом в их просветах':'erythrocytes_lysis_in_lumens',
 'Периваскулярные кровоизлияния':'perivascular_hemorrhage',
 'Тромбоэмболы в просветах ветвей легочной артерии':'pulmonary_artery_thromboemboli',
 'Фибриновые тромбы в просветах ветвей легочной артерии':'pulmonary_artery_fibrin_clots',
 'Организующиеся тромбы в просветах ветвей легочной артерии':'pulmonary_artery_trombs',
 'Фибриновые тромбы  в просветах ветвей легочных вен':'pulmonary_veins_fibrin_clots',
 'Организующиеся тромбы в просветах ветвей легочных вен':'pulmonary_veins_trombs',
 'Внутриальвеолярные кровоизлияния':'intraalveolar_hemorrhage',
 'Скопление фибрина в просветах альвеол':'alveoli_fibrin_accumulation',
 'Лимфо-макрофагальная инфильтрация интраальвеолярно':'lympho_macrophage_infiltration_intra-alveolar',
 'Гиалиновые мембраны (протяжённость)':'hyaline_membranes_length',
 'Гиалиновые мембраны толщина (% S от Р)':'hyaline_membranes_percent',
 'Атипичные альвеолоциты':'atypical_alveolocytes',
 'Десквамированные уродливой формы альвеолоциты 2 типа с интрацитоплазматическими включениями в просвете альвеол':'desquamated_ugly_type_2_alveolocytes_with_intracytoplasmic_inclusions_in_the_lumen_of_the_alveoli',
 'Симпласты':'symplasts',
 'Плоскоклеточная метаплазия':'squamous_metaplasia',
 'Десквамация эпителия бронхов':'bronchial_epithelium_desquamation',
 'Спазм мелких бронхов':'small_bronchial_spasm',
 'Десквамированный альвеолярный эпителий в просветах альвеол':'desquamated_alveolar_epithelium_in_the_lumen_of_the_alveoli',
 'Амилоидные тельца':'amyloid_bodies',
 'Фиброз межальвеолярных перегородок':'fibrosis_of_interalveolar_septa',
 'Интерстициальный отёк':'interstitial_edema',
 'Утолщение межальвеолярных перегородок за счет склероза':'thickening ofthe_interalveolar_septa_due_to_sclerosis',
 'Лимфо-макрофагальная инфильтрация межальвеолярных перегородок ':'lympho_macrophage_infiltration_of_interalveolar_septa',
 'Аспирационная пневмония (инородные частицы в просвете терминальной бронхиолы)':'aspiration_pneumonia',
}
